import { v4 as uuid } from "uuid";

export const MOCK_PRODUCTS = [
  {
    id: uuid(),
    provider: "Balwin",
    name: "Uncapped 15/15Mbps",
    price: 439,
    download: 15,
    upload: 15,
    link: "https://www.balwinfibre.co.za/",
  },
  {
    id: uuid(),
    provider: "Balwin",
    name: "Uncapped 30/30Mbps",
    price: 599,
    download: 30,
    upload: 30,
    link: "https://www.balwinfibre.co.za/",
  },
  {
    id: uuid(),
    provider: "Clear Access",
    name: "Uncapped 20/20Mbps",
    price: 480,
    download: 20,
    upload: 20,
    link: "https://www.clearaccess.co.za/",
  },
  {
    id: uuid(),
    provider: "Comtel",
    name: "Uncapped 50/50Mbps",
    price: 850,
    download: 50,
    upload: 50,
    link: "https://www.comtel.co.za/",
  },
  {
    id: uuid(),
    provider: "Cybersmart",
    name: "Uncapped 100/100Mbps",
    price: 1299,
    download: 100,
    upload: 100,
    link: "https://www.cybersmart.co.za/",
  },
  {
    id: uuid(),
    provider: "DNATel",
    name: "Uncapped 30/30Mbps",
    price: 650,
    download: 30,
    upload: 30,
    link: "https://www.dnatel.co.za/",
  },
  {
    id: uuid(),
    provider: "Fibre Suburb Networks",
    name: "Uncapped 100/100Mbps",
    price: 1200,
    download: 100,
    upload: 100,
    link: "https://www.fibresuburb.co.za/",
  },
  {
    id: uuid(),
    provider: "Frogfoot",
    name: "Uncapped 500/500Mbps",
    price: 1999,
    download: 500,
    upload: 500,
    link: "https://www.frogfootfibre.co.za/",
  },
  {
    id: uuid(),
    provider: "Frogfoot Air",
    name: "Uncapped 250/250Mbps",
    price: 1499,
    download: 250,
    upload: 250,
    link: "https://www.frogfootair.co.za/",
  },
  {
    id: uuid(),
    provider: "Gaia Fibonacci",
    name: "Uncapped 200/200Mbps",
    price: 1399,
    download: 200,
    upload: 200,
    link: "https://www.gaiafibonacci.co.za/",
  },
  {
    id: uuid(),
    provider: "LightStruck",
    name: "Uncapped 120/120Mbps",
    price: 900,
    download: 120,
    upload: 120,
    link: "https://www.lightstruck.co.za/",
  },
  {
    id: uuid(),
    provider: "Link Layer",
    name: "Uncapped 50/50Mbps",
    price: 800,
    download: 50,
    upload: 50,
    link: "https://www.linklayer.co.za/",
  },
  {
    id: uuid(),
    provider: "MFN",
    name: "Uncapped 100/100Mbps",
    price: 1400,
    download: 100,
    upload: 100,
    link: "https://www.mfn.co.za/",
  },
  {
    id: uuid(),
    provider: "MFN Nova",
    name: "Uncapped 200/200Mbps",
    price: 1800,
    download: 200,
    upload: 200,
    link: "https://www.mfn.co.za/nova",
  },
  {
    id: uuid(),
    provider: "Mitsol",
    name: "Uncapped 30/30Mbps",
    price: 600,
    download: 30,
    upload: 30,
    link: "https://www.mitsol.co.za/",
  },
  {
    id: uuid(),
    provider: "Octotel",
    name: "Uncapped 50/50Mbps",
    price: 750,
    download: 50,
    upload: 50,
    link: "https://www.octotel.co.za/",
  },
  {
    id: uuid(),
    provider: "Openserve",
    name: "Uncapped 120/120Mbps",
    price: 950,
    download: 120,
    upload: 120,
    link: "https://www.openserve.co.za/",
  },
  {
    id: uuid(),
    provider: "Openserve Web Connect",
    name: "Uncapped 100/100Mbps",
    price: 900,
    download: 100,
    upload: 100,
    link: "https://www.openserve.co.za/web-connect",
  },
  {
    id: uuid(),
    provider: "ThinkSpeed",
    name: "Uncapped 200/200Mbps",
    price: 1700,
    download: 200,
    upload: 200,
    link: "https://www.thinkspeed.co.za/",
  },
  {
    id: uuid(),
    provider: "Vodacom",
    name: "Uncapped 250/250Mbps",
    price: 1500,
    download: 250,
    upload: 250,
    link: "https://www.vodacom.co.za/fibre",
  },
  {
    id: uuid(),
    provider: "Vumatel",
    name: "Uncapped 500/500Mbps",
    price: 2000,
    download: 500,
    upload: 500,
    link: "https://www.vumatel.co.za/",
  },
];